package com.martin.storage.customUI

abstract class UserInterface(initialName: String, var identifier: String = "") {
    open var name: String = initialName
    /**
     * A private set that stores all currently used user interface IDs.
     * This ensures that every newly created user interface has a unique ID, which is critical
     * for stable and efficient list management in Compose's `LazyColumn`.
     */
    companion object {
        private val existingIds = mutableSetOf<String>()
    }

    init {
        // This block guarantees that every user interface instance has a unique ID.
        // If a valid, unique ID is provided during construction, it is used.
        if (existingIds.add(identifier) && identifier != "" ) {
            this.identifier = identifier
        } else {
            // Otherwise, a new unique ID is generated by trying different combinations
            // until an unused one is found and added to the set of existing IDs.
            var n = 1
            var tempId = "$initialName-$n"
            while (!existingIds.add(tempId)) {
                n++
                tempId = "$initialName-$n-$initialName"
            }
            this.identifier = tempId
        }
    }
}
