package com.martin.storage.data

import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.martin.storage.R
import kotlinx.serialization.Serializable

// --- Data Models ---

/**
 * A serializable data class that represents a storage item in its persistent state.
 * This class is used for saving and loading item data from sources like DataStore or Firebase.
 *
 * It's a `data class` to automatically get `equals()`, `hashCode()`, and other utility functions,
 * which are essential for comparing and managing items in collections. The `@Serializable` annotation
 * enables the Kotlinx Serialization library to convert this class to and from JSON format.
 *
 * @property name The name of the item (e.g., "Milk").
 * @property img A string that holds the path to the item's image, which can be a local file path or a drawable resource ID.
 * @property count The quantity of the item.
 * @property unit The unit of measurement (e.g., "Liters", "gallons").
 * @property pgIndex The zero-based index of the tab (e.g., Fridge, Pantry) where the item is stored.
 * @property id A unique identifier for the item, necessary for stable list management and database operations.
 * @property decrement The value by which the `count` automatically decreases.
 * @property decrementInterval The frequency in days at which the `decrement` is applied.
 */
@Serializable
data class LocalRowItem(
    val name: String,
    val img: String,
    val count: Int,
    val unit: String,
    val pgIndex: Int,
    val id: String,
    val decrement: Int = 1,
    val decrementInterval: Int
)

/**
 * A stateful class that represents a single item in the Compose UI.
 * This class acts as the single source of truth for the UI layer. It uses Compose's `State` delegates
 * (`mutableStateOf`, `mutableIntStateOf`) to make its properties observable. Any composable that reads
 * these properties will automatically recompose when their values change, keeping the UI in sync.
 *
 * @param initialName The initial name for a newly created item.
 * @param initialImg The default image resource or path.
 * @param initialCount The starting quantity.
 * @param initialUnit The initial unit of measurement.
 * @param initialPgIndex The default tab index.
 * @param id An optional existing ID. If not provided, a unique one is generated.
 * @param display A flag indicating whether the item should be displayed, useful for filtering in search results.
 * @param decrement The amount by which the count automatically decreases.
 * @param decrementInterval The period in days for the automatic decrement.
 */
class RowItem(
    initialName: String = "New item",
    initialImg: String = R.drawable.sunflowers.toString(),
    initialCount: Int = 0,
    initialUnit: String = "",
    initialPgIndex: Int = 0,
    id: String? = null, // Nullable to allow for new item creation
    var display: Boolean = true,
    var decrement: Int = 1,
    var decrementInterval: Int = 1
) {
    /**
     * A secondary constructor that creates a `RowItem` for the UI layer from a `LocalRowItem` from the data layer.
     * This simplifies the process of converting persisted data into a stateful UI object.
     */
    constructor(localItem: LocalRowItem) : this(
        initialName = localItem.name,
        initialImg = localItem.img,
        initialCount = localItem.count,
        initialUnit = localItem.unit,
        initialPgIndex = localItem.pgIndex,
        id = localItem.id,
        decrement = localItem.decrement,
        decrementInterval = localItem.decrementInterval
    )

    companion object {
        /**
         * A global, observable state that holds the `RowItem` currently being edited.
         * When this value is set to a `RowItem`, the `EditItemDialog` is displayed.
         * When it is `null`, the dialog is hidden.
         */
        var itemToEdit = mutableStateOf<RowItem?>(null)

        /**
         * A private set that stores all currently used `RowItem` IDs.
         * This ensures that every newly created `RowItem` has a unique ID, which is critical
         * for stable and efficient list management in Compose's `LazyColumn`.
         */
        private val existingIds = mutableSetOf<String>()
    }

    val id: String
    var name by mutableStateOf(initialName)
    var count by mutableIntStateOf(initialCount)
    var unit by mutableStateOf(initialUnit)
    var img by mutableStateOf(initialImg)
    var pgIndex by mutableIntStateOf(initialPgIndex)

    init {
        // This block guarantees that every RowItem instance has a unique ID.
        // If a valid, unique ID is provided during construction, it is used.
        if (id != null && existingIds.add(id)) {
            this.id = id
        } else {
            // Otherwise, a new unique ID is generated by trying different combinations
            // until an unused one is found and added to the set of existing IDs.
            var n = 1
            var tempId = "itemNum$n-P$initialPgIndex"
            while (!existingIds.add(tempId)) {
                n++
                tempId = "$initialName-$n-$initialPgIndex"
            }
            this.id = tempId
        }
    }

    /**
     * Increases the item's count by one.
     */
    fun increaseCount() {
        count++
    }

    /**
     * Decreases the item's count by the `decrement` value, preventing it from going below zero.
     */
    fun decreaseCount() {
        if (count > 0) {
            count -= decrement
            if (count < 0) {
                count = 0
            }
        }
    }

    /**
     * Converts this UI-layer `RowItem` into a data-layer `LocalRowItem` to be persisted.
     * @return A `LocalRowItem` instance containing the current data, ready for serialization.
     */
    fun toLocalRowItem(): LocalRowItem {
        return LocalRowItem(
            name = this.name,
            img = this.img,
            count = this.count,
            unit = this.unit,
            pgIndex = this.pgIndex,
            id = this.id,
            decrement = this.decrement,
            decrementInterval = this.decrementInterval
        )
    }

    /**
     * Calculates and applies an automatic decrement to the item's count based on the
     * time that has passed since the app was last opened.
     *
     * @param last The timestamp (as a String) of the last time the app was opened.
     * @param now The current timestamp (as a String).
     */
    fun updateDecrement(last: String, now: String) {
        val lastMillis = last.toLongOrNull()
        val nowMillis = now.toLongOrNull()

        if (lastMillis == null || nowMillis == null) {
            Log.e("RowItem", "Invalid timestamps provided for decrement update.")
            return
        }

        val diffInMillis = nowMillis - lastMillis
        // Calculate the number of full days that have elapsed.
        val daysPassed = diffInMillis / (1000 * 60 * 60 * 24)

        Log.d("RowItem", "Days passed since last open for item '$name': $daysPassed")

        if (daysPassed > 0 && decrementInterval > 0) {
            // Determine how many times the decrement interval has occurred.
            val timesToDecrement = daysPassed / decrementInterval

            if (timesToDecrement > 0) {
                // Apply the total calculated decrement to the count.
                val totalDecrement = (decrement * timesToDecrement).toInt()
                // `coerceAtLeast(0)` ensures the count does not drop below zero.
                count = (count - totalDecrement).coerceAtLeast(0)
                Log.d("RowItem", "Decremented '$name' by $totalDecrement over $daysPassed days. New count: $count")
            }
        }
    }
}
